/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BudgetRegistry {
  export type TransactionStruct = {
    id: BigNumberish;
    commune: string;
    txType: BigNumberish;
    category: string;
    amount: BigNumberish;
    timestamp: BigNumberish;
    description: string;
    recorder: AddressLike;
  };

  export type TransactionStructOutput = [
    id: bigint,
    commune: string,
    txType: bigint,
    category: string,
    amount: bigint,
    timestamp: bigint,
    description: string,
    recorder: string
  ] & {
    id: bigint;
    commune: string;
    txType: bigint;
    category: string;
    amount: bigint;
    timestamp: bigint;
    description: string;
    recorder: string;
  };
}

export interface BudgetRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMMUNE_ADMIN"
      | "DEFAULT_ADMIN_ROLE"
      | "communeBalance"
      | "getBalance"
      | "getRoleAdmin"
      | "getTotalTransactions"
      | "getTransactionCount"
      | "getTransactions"
      | "grantCommuneAdmin"
      | "grantRole"
      | "hasRole"
      | "isCommuneAdmin"
      | "recordExpense"
      | "recordRevenue"
      | "renounceRole"
      | "revokeCommuneAdmin"
      | "revokeRole"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommuneAdminGranted"
      | "CommuneAdminRevoked"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TransactionRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMMUNE_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "communeBalance",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getBalance", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantCommuneAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCommuneAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordExpense",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordRevenue",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCommuneAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMMUNE_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "communeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantCommuneAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCommuneAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCommuneAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace CommuneAdminGrantedEvent {
  export type InputTuple = [account: AddressLike, grantedBy: AddressLike];
  export type OutputTuple = [account: string, grantedBy: string];
  export interface OutputObject {
    account: string;
    grantedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommuneAdminRevokedEvent {
  export type InputTuple = [account: AddressLike, revokedBy: AddressLike];
  export type OutputTuple = [account: string, revokedBy: string];
  export interface OutputObject {
    account: string;
    revokedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    commune: string,
    txType: BigNumberish,
    category: string,
    amount: BigNumberish,
    timestamp: BigNumberish,
    description: string,
    recorder: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    commune: string,
    txType: bigint,
    category: string,
    amount: bigint,
    timestamp: bigint,
    description: string,
    recorder: string
  ];
  export interface OutputObject {
    id: bigint;
    commune: string;
    txType: bigint;
    category: string;
    amount: bigint;
    timestamp: bigint;
    description: string;
    recorder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BudgetRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BudgetRegistry;
  waitForDeployment(): Promise<this>;

  interface: BudgetRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMMUNE_ADMIN: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  communeBalance: TypedContractMethod<[arg0: string], [bigint], "view">;

  getBalance: TypedContractMethod<[commune: string], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalTransactions: TypedContractMethod<[], [bigint], "view">;

  getTransactionCount: TypedContractMethod<[commune: string], [bigint], "view">;

  getTransactions: TypedContractMethod<
    [commune: string],
    [BudgetRegistry.TransactionStructOutput[]],
    "view"
  >;

  grantCommuneAdmin: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isCommuneAdmin: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  recordExpense: TypedContractMethod<
    [
      commune: string,
      category: string,
      amount: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  recordRevenue: TypedContractMethod<
    [
      commune: string,
      category: string,
      amount: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeCommuneAdmin: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMMUNE_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "communeBalance"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[commune: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalTransactions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransactionCount"
  ): TypedContractMethod<[commune: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransactions"
  ): TypedContractMethod<
    [commune: string],
    [BudgetRegistry.TransactionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantCommuneAdmin"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCommuneAdmin"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordExpense"
  ): TypedContractMethod<
    [
      commune: string,
      category: string,
      amount: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordRevenue"
  ): TypedContractMethod<
    [
      commune: string,
      category: string,
      amount: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCommuneAdmin"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "CommuneAdminGranted"
  ): TypedContractEvent<
    CommuneAdminGrantedEvent.InputTuple,
    CommuneAdminGrantedEvent.OutputTuple,
    CommuneAdminGrantedEvent.OutputObject
  >;
  getEvent(
    key: "CommuneAdminRevoked"
  ): TypedContractEvent<
    CommuneAdminRevokedEvent.InputTuple,
    CommuneAdminRevokedEvent.OutputTuple,
    CommuneAdminRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionRecorded"
  ): TypedContractEvent<
    TransactionRecordedEvent.InputTuple,
    TransactionRecordedEvent.OutputTuple,
    TransactionRecordedEvent.OutputObject
  >;

  filters: {
    "CommuneAdminGranted(address,address)": TypedContractEvent<
      CommuneAdminGrantedEvent.InputTuple,
      CommuneAdminGrantedEvent.OutputTuple,
      CommuneAdminGrantedEvent.OutputObject
    >;
    CommuneAdminGranted: TypedContractEvent<
      CommuneAdminGrantedEvent.InputTuple,
      CommuneAdminGrantedEvent.OutputTuple,
      CommuneAdminGrantedEvent.OutputObject
    >;

    "CommuneAdminRevoked(address,address)": TypedContractEvent<
      CommuneAdminRevokedEvent.InputTuple,
      CommuneAdminRevokedEvent.OutputTuple,
      CommuneAdminRevokedEvent.OutputObject
    >;
    CommuneAdminRevoked: TypedContractEvent<
      CommuneAdminRevokedEvent.InputTuple,
      CommuneAdminRevokedEvent.OutputTuple,
      CommuneAdminRevokedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TransactionRecorded(uint256,string,uint8,string,uint256,uint256,string,address)": TypedContractEvent<
      TransactionRecordedEvent.InputTuple,
      TransactionRecordedEvent.OutputTuple,
      TransactionRecordedEvent.OutputObject
    >;
    TransactionRecorded: TypedContractEvent<
      TransactionRecordedEvent.InputTuple,
      TransactionRecordedEvent.OutputTuple,
      TransactionRecordedEvent.OutputObject
    >;
  };
}
