name: budgetouvert
description: Application de transparence budgétaire citoyenne - République de Côte d'Ivoire
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.0.0

  # State management
  provider: ^6.1.2

  font_awesome_flutter: ^10.7.0

  flutter_svg: ^2.2.4

  # UI / animations
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.2.3

  # Utilitaires
  cupertino_icons: ^1.0.9
  intl: ^0.20.2
  mobile_scanner: ^7.2.0
  shared_preferences: ^2.5.5
  http: ^1.6.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  audioplayers: ^6.6.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  image_picker: ^1.2.2
  permission_handler: ^12.0.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true



  # Assets
  assets:
    - assets/images/
