name: budgetouvert
description: Application de transparence budgétaire citoyenne - République de Côte d'Ivoire
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.0.0

  # State management
  provider: ^6.1.2

  font_awesome_flutter: ^10.7.0

  flutter_svg: ^2.0.10

  # UI / animations
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.2.3

  # Utilitaires
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  mobile_scanner: ^7.2.0


  # Audio multilingue
  audioplayers: ^6.1.0

  # Carte interactive
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

    # Signalement — image picker
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

    # Utilitaires
  
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1

  # Réseau / API
  http: ^1.2.1

  # Persistance session
  shared_preferences: ^2.2.3

  # Géolocalisation
  geolocator: ^12.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true



  # Assets
  assets:
    - assets/images/


flutter_native_splash:
  color: "#2D6B4A" # couleur de fond
  image: assets/images/logo_.png # ton logo (PNG recommandé)
  android: true
  ios: true

  android_12:
    image: assets/images/logo_.png
    icon_background_color: "#0F2E1E"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_1.png"