// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3iS33jly82x36BDBfhHBp4H02f7aUQWY',
    appId: '1:648631167403:web:c3eed417beee270ee44aee',
    messagingSenderId: '648631167403',
    projectId: 'budget-ouvert',
    authDomain: 'budget-ouvert.firebaseapp.com',
    storageBucket: 'budget-ouvert.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7rx1tgrRvpIIPudeNcn1AcVn6ja3-lDs',
    appId: '1:648631167403:android:53103e551277067be44aee',
    messagingSenderId: '648631167403',
    projectId: 'budget-ouvert',
    storageBucket: 'budget-ouvert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4UyjHh1BVX129bFaPLd0tzAdeT5V3S0',
    appId: '1:648631167403:ios:8f225d5527c30a91e44aee',
    messagingSenderId: '648631167403',
    projectId: 'budget-ouvert',
    storageBucket: 'budget-ouvert.firebasestorage.app',
    iosBundleId: 'com.example.budgetOuvert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy4UyjHh1BVX129bFaPLd0tzAdeT5V3S0',
    appId: '1:648631167403:ios:8f225d5527c30a91e44aee',
    messagingSenderId: '648631167403',
    projectId: 'budget-ouvert',
    storageBucket: 'budget-ouvert.firebasestorage.app',
    iosBundleId: 'com.example.budgetOuvert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3iS33jly82x36BDBfhHBp4H02f7aUQWY',
    appId: '1:648631167403:web:6d69201b89453ea5e44aee',
    messagingSenderId: '648631167403',
    projectId: 'budget-ouvert',
    authDomain: 'budget-ouvert.firebaseapp.com',
    storageBucket: 'budget-ouvert.firebasestorage.app',
  );
}
